# Generated by Django 5.2 on 2025-04-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
